/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projecttm;

import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Dragon
 */
public class EditTable extends javax.swing.JFrame {

    /**
     * Creates new form EditTable
     */
    public EditTable() {
         Vector<String> ShowAll = new Vector<>();
         ShowAll = Sort.ShowAll();
               
        
        initComponents();
        
        jList1.setListData(ShowAll);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setToolTipText("Edit");
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Edit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 264, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        NewJFrame FileManager = new NewJFrame();
        FileManager.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Filer.Open();
        Vector<String> Show = new Vector<>();
        //Vector<String> Delete = new Vector<>();
        Show = Filer.Read();
        //Delete = Filer.Read();
        
        String EditData = Show.get(jList1.getAnchorSelectionIndex());
        Show.remove(jList1.getAnchorSelectionIndex());
        Filer.CloseW();
        
         Filer.New();
        Filer.Open();
        String DB = "";
        for(int i=0; i<Show.size(); i++){
            DB += Show.get(i);
        }
         Filer.myfile.format(DB);
        Filer.CloseW();
        Filer.Close();
         Filer.Open();
         Show = Filer.Read();
         jList1.setListData(Show);
        
        
        
        
        
        String[] Data = EditData.split(" ");
        System.out.println(EditData);
        System.out.println(Data[0]);
        
        if (DataFormats.valueOf(Data[0]).getDataType().equals("Image")){
            NewJFrame5 Photo = new NewJFrame5();
            Photo.setTexts(Data[0], Data[1], Data[2], Data[3], Data[4], Data[5], Data[6],Data[7]);
            setVisible(false);
            Photo.setVisible(true);
        }
        else if (DataFormats.valueOf(Data[0]).getDataType().equals("Audio")){
            NewJFrame6 Audio = new NewJFrame6();
            Audio.setTexts(Data[0], Data[1], Data[2], Data[3], Data[4], Data[5], Data[6],Data[7],Data[8]);
            setVisible(false);
            Audio.setVisible(true);
        }
         else if (DataFormats.valueOf(Data[0]).getDataType().equals("Ebook")){
            NewJFrame8 Ebook = new NewJFrame8();
            Ebook.setTexts(Data[0], Data[1], Data[2], Data[3], Data[4], Data[5], Data[6],Data[7], Data[8], Data[9]);
            setVisible(false);
            Ebook.setVisible(true);
        }
         else if (DataFormats.valueOf(Data[0]).getDataType().equals("Video")){
            NewJFrame7 Video = new NewJFrame7();
            Video.setTexts(Data[0], Data[1], Data[2], Data[3], Data[4], Data[5], Data[6],Data[7], Data[8], Data[9]);
            setVisible(false);
            Video.setVisible(true);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
